version: '3.7'

services:
  curueno-porma-warbot:
    container_name: ${DOCKER_CONTAINER_NAME}
    hostname: ${DOCKER_CONTAINER_NAME}
    restart: always
    image: ${REGISTRY}:${REGISTRY_PORT}/${DOCKER_CONTAINER_NAME}_image
    env_file:
      - .env
    volumes:
      - ./:/src/
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "${WARBOT_API_PORT}:8000"
    logging:
      driver: 'json-file'
      options:
        max-size: 50m
        max-file: '2'

  mysql:
    image: mysql:8-oracle
    platform: linux/amd64
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    env_file:
      - .env
    ports:
      - "${ADMINER_PORT}:8080"